In [15]:
# Data Manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Ignore Warnings
import warnings
warnings.filterwarnings("ignore")

In [18]:
matches = pd.read_csv("matches.csv.xls")
deliveries = pd.read_csv("deliveries.csv.xls")

In [19]:
matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [20]:
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [21]:
matches.shape

(1095, 20)

In [22]:
deliveries.shape

(260920, 17)

In [23]:
matches.columns.tolist()

['id',
 'season',
 'city',
 'date',
 'match_type',
 'player_of_match',
 'venue',
 'team1',
 'team2',
 'toss_winner',
 'toss_decision',
 'winner',
 'result',
 'result_margin',
 'target_runs',
 'target_overs',
 'super_over',
 'method',
 'umpire1',
 'umpire2']

In [24]:
deliveries.columns.tolist()

['match_id',
 'inning',
 'batting_team',
 'bowling_team',
 'over',
 'ball',
 'batter',
 'bowler',
 'non_striker',
 'batsman_runs',
 'extra_runs',
 'total_runs',
 'extras_type',
 'is_wicket',
 'player_dismissed',
 'dismissal_kind',
 'fielder']

In [25]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

In [26]:
deliveries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB

In [27]:
matches.describe()

                 id  result_margin  target_runs  target_overs
count  1.095000e+03    1076.000000  1092.000000   1092.000000
mean   9.048283e+05      17.259294   165.684066     19.759341
std    3.677402e+05      21.787444    33.427048      1.581108
min    3.359820e+05       1.000000    43.000000      5.000000
25%    5.483315e+05       6.000000   146.000000     20.000000
50%    9.809610e+05       8.000000   166.000000     20.000000
75%    1.254062e+06      20.000000   187.000000     20.000000
max    1.426312e+06     146.000000   288.000000     20.000000

In [28]:
deliveries.describe()

,match_id,inning,over,ball,batsman_runs,extra_runs,total_runs,is_wicket
count,2.609200e+05,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000
mean,9.070665e+05,1.483531,9.197677,3.624486,1.265001,0.067806,1.332807,0.049632
std,3.679913e+05,0.502643,5.683484,1.814920,1.639298,0.343265,1.626416,0.217184
min,3.359820e+05,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,5.483340e+05,1.000000,4.000000,2.000000,0.000000,0.000000,0.000000,0.000000
50%,9.809670e+05,1.000000,9.000000,4.000000,1.000000,0.000000,1.000000,0.000000
75%,1.254066e+06,2.000000,14.000000,5.000000,1.000000,0.000000,1.000000,0.000000
max,1.426312e+06,6.000000,19.000000,11.000000,6.000000,7.000000,7.000000,1.000000

In [29]:
matches.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [30]:
matches.isnull().sum().sort_values(ascending=False)

method             1074
city                 51
result_margin        19
winner                5
player_of_match       5
target_overs          3
target_runs           3
id                    0
umpire1               0
super_over            0
result                0
toss_decision         0
season                0
toss_winner           0
team2                 0
team1                 0
venue                 0
match_type            0
date                  0
umpire2               0
dtype: int64

In [31]:
deliveries.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [32]:
deliveries.isnull().sum().sort_values(ascending=False)

fielder             251566
dismissal_kind      247970
player_dismissed    247970
extras_type         246795
batsman_runs             0
is_wicket                0
total_runs               0
extra_runs               0
match_id                 0
inning                   0
bowler                   0
batter                   0
ball                     0
over                     0
bowling_team             0
batting_team             0
non_striker              0
dtype: int64

In [35]:
print("Total Seasons:", matches["season"].nunique())
print("Seasons Covered:")
print(sorted(matches["season"].unique()))

Total Seasons: 17
Seasons Covered:
['2007/08', '2009', '2009/10', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020/21', '2021', '2022', '2023', '2024']

In [36]:
teams = pd.unique(
    matches[
        ["team1", "team2"]
    ].values.ravel()
)

len(teams)

19

In [37]:
matches.shape
deliveries.shape

matches.columns.tolist()
deliveries.columns.tolist()

matches.isnull().sum().sort_values(ascending=False).head(10)

method             1074
city                 51
result_margin        19
winner                5
player_of_match       5
target_overs          3
target_runs           3
id                    0
umpire1               0
super_over            0
dtype: int64

In [38]:
# Phase 2: Data Cleaning & Preprocessing

In [39]:
print("Matches Dataset Missing Values")
matches.isnull().sum().sort_values(ascending=False)

Matches Dataset Missing Values

method             1074
city                 51
result_margin        19
winner                5
player_of_match       5
target_overs          3
target_runs           3
id                    0
umpire1               0
super_over            0
result                0
toss_decision         0
season                0
toss_winner           0
team2                 0
team1                 0
venue                 0
match_type            0
date                  0
umpire2               0
dtype: int64

In [40]:
matches["city"].isnull().sum()

np.int64(51)

In [41]:
matches["city"] = matches["city"].fillna("Unknown")

In [43]:
matches["player_of_match"].isnull().sum()

np.int64(5)

In [44]:
matches["player_of_match"] = matches["player_of_match"].fillna("No Award")

In [46]:
matches[matches["winner"].isnull()]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
241,501265,2011,Delhi,2011-05-21,League,No Award,Feroz Shah Kotla,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,NaN,no result,NaN,NaN,NaN,N,NaN,SS Hazare,RJ Tucker
485,829763,2015,Bangalore,2015-04-29,League,No Award,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,no result,NaN,NaN,NaN,N,NaN,JD Cloete,PG Pathak
511,829813,2015,Bangalore,2015-05-17,League,No Award,M Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,NaN,no result,NaN,188.0,20.0,N,NaN,HDPK Dharmasena,K Srinivasan
744,1178424,2019,Bengaluru,2019-04-30,League,No Award,M.Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,no result,NaN,63.0,5.0,N,NaN,NJ Llong,UV Gandhe
994,1359519,2023,Lucknow,2023-05-03,League,No Award,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Chennai Super Kings,Chennai Super Kings,field,NaN,no result,NaN,NaN,NaN,N,NaN,AK Chaudhary,NA Patwardhan

In [47]:
matches["winner"] = matches["winner"].fillna("No Result")

In [51]:
matches[
    ["target_runs","target_overs"]
].isnull().sum()

target_runs     3
target_overs    3
dtype: int64

In [52]:
matches["target_runs"] = matches["target_runs"].fillna(0)
matches["target_overs"] = matches["target_overs"].fillna(0)

In [54]:
matches["method"].value_counts(dropna=False)

method
NaN    1074
D/L      21
Name: count, dtype: int64

In [55]:
deliveries["dismissal_kind"] = (
    deliveries["dismissal_kind"]
    .fillna("not out")
)

In [56]:
deliveries["dismissal_kind"].value_counts().head()

dismissal_kind
not out    247970
caught       8063
bowled       2212
run out      1114
lbw           800
Name: count, dtype: int64

In [57]:
matches.isnull().sum().sort_values(ascending=False).head(10)

method           1074
result_margin      19
id                  0
season              0
umpire1             0
super_over          0
target_overs        0
target_runs         0
result              0
winner              0
dtype: int64

In [58]:
deliveries.isnull().sum().sort_values(ascending=False).head(10)

fielder             251566
player_dismissed    247970
extras_type         246795
batsman_runs             0
dismissal_kind           0
is_wicket                0
total_runs               0
extra_runs               0
match_id                 0
inning                   0
dtype: int64

In [59]:
matches.duplicated().sum()

np.int64(0)

In [60]:
deliveries.duplicated().sum()

np.int64(0)

In [61]:
sorted(matches['team1'].unique())

['Chennai Super Kings',
 'Deccan Chargers',
 'Delhi Capitals',
 'Delhi Daredevils',
 'Gujarat Lions',
 'Gujarat Titans',
 'Kings XI Punjab',
 'Kochi Tuskers Kerala',
 'Kolkata Knight Riders',
 'Lucknow Super Giants',
 'Mumbai Indians',
 'Pune Warriors',
 'Punjab Kings',
 'Rajasthan Royals',
 'Rising Pune Supergiant',
 'Rising Pune Supergiants',
 'Royal Challengers Bangalore',
 'Royal Challengers Bengaluru',
 'Sunrisers Hyderabad']

In [66]:
matches.replace({
    "Delhi Daredevils":"Delhi Capitals",
    "Kings XI Punjab":"Punjab Kings",
    "Rising Pune Supergiants":"Rising Pune Supergiant",
    "Gujarat Lions":"Gujarat Titans",
    "Royal Challengers Bangalore":"Royal Challengers Bengaluru",
    "Pune Warriors":"Rising Pune Supergiant"
}, inplace=True)

In [67]:
sorted(matches['team1'].unique())

['Chennai Super Kings',
 'Deccan Chargers',
 'Delhi Capitals',
 'Gujarat Titans',
 'Kochi Tuskers Kerala',
 'Kolkata Knight Riders',
 'Lucknow Super Giants',
 'Mumbai Indians',
 'Punjab Kings',
 'Rajasthan Royals',
 'Rising Pune Supergiant',
 'Royal Challengers Bengaluru',
 'Sunrisers Hyderabad']

In [68]:
matches['date'] = pd.to_datetime(matches['date'])
matches['date'].dtype

dtype('<M8[ns]')

In [69]:
matches[['target_runs','target_overs']].describe()

       target_runs  target_overs
count  1095.000000   1095.000000
mean    165.230137     19.705205
std      34.487313      1.887000
min       0.000000      0.000000
25%     146.000000     20.000000
50%     166.000000     20.000000
75%     187.000000     20.000000
max     288.000000     20.000000

In [70]:
deliveries[['batsman_runs','extra_runs','total_runs']].describe()

        batsman_runs     extra_runs     total_runs
count  260920.000000  260920.000000  260920.000000
mean        1.265001       0.067806       1.332807
std         1.639298       0.343265       1.626416
min         0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000
50%         1.000000       0.000000       1.000000
75%         1.000000       0.000000       1.000000
max         6.000000       7.000000       7.000000

In [71]:
(deliveries['batsman_runs'] > 6).sum()

np.int64(0)

In [72]:
deliveries['over'].min()
deliveries['over'].max()

19

In [73]:
deliveries['is_wicket'].value_counts()

is_wicket
0    247970
1     12950
Name: count, dtype: int64

In [74]:
deliveries['is_wicket'].unique()

array([0, 1])

In [75]:
deliveries['extras_type'].value_counts(dropna=False)

extras_type
NaN        246795
wides        8380
legbyes      4001
noballs      1069
byes          673
penalty         2
Name: count, dtype: int64

In [82]:
matches.duplicated().sum()

np.int64(0)

In [83]:
deliveries.duplicated().sum()

np.int64(0)

In [84]:
sorted(matches['team1'].unique())

['Chennai Super Kings',
 'Deccan Chargers',
 'Delhi Capitals',
 'Gujarat Titans',
 'Kochi Tuskers Kerala',
 'Kolkata Knight Riders',
 'Lucknow Super Giants',
 'Mumbai Indians',
 'Punjab Kings',
 'Rajasthan Royals',
 'Rising Pune Supergiant',
 'Royal Challengers Bengaluru',
 'Sunrisers Hyderabad']

In [85]:
print("Min Over:", deliveries['over'].min())
print("Max Over:", deliveries['over'].max())

Min Over: 0
Max Over: 19

In [86]:
matches['result_margin'].describe()

count    1076.000000
mean       17.259294
std        21.787444
min         1.000000
25%         6.000000
50%         8.000000
75%        20.000000
max       146.000000
Name: result_margin, dtype: float64